name: Build and Push Docker Images by BartekZ

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Configure Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push arm64v8 and amd64 image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bartekz99hd/fullstack_bartekz:latest
          platforms: |
            linux/arm64/v8
            linux/amd64
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_CLI_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          