name: Build and Push Docker Images by BartekZ

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and push images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            bartekz99hd/fullstack_bartekz:latest
            bartekz99hd/fullstack_bartekz:arm64v8-latest
          platforms: |
            linux/amd64
            linux/arm64/v8
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}